import { GoogleGenAI } from "@google/genai";

export const config = {
  runtime: 'edge', // Optional: Use Edge runtime for faster cold starts, or remove for Node.js
};

export default async function handler(req: Request) {
  if (req.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  try {
    const { images, prompt, aspectRatio, modelName } = await req.json();

    // 1. Security & Validation
    if (!process.env.GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: 'Server misconfiguration: API Key missing' }), { status: 500 });
    }

    if (!prompt || typeof prompt !== 'string') {
      return new Response(JSON.stringify({ error: 'Prompt is required' }), { status: 400 });
    }

    if (!images || !Array.isArray(images) || images.length === 0) {
      return new Response(JSON.stringify({ error: 'At least one reference image is required' }), { status: 400 });
    }

    // 2. Initialize Gemini (Server-Side Only)
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    // 3. Prepare Content Parts
    const parts: any[] = [{ text: prompt }];

    // Clean base64 strings if necessary (remove data:image/...;base64, prefix)
    // The SDK often handles this, but strictly formatting it ensures compatibility.
    images.forEach((imgDataUrl: string) => {
      const base64Data = imgDataUrl.split(',')[1] || imgDataUrl;
      parts.push({
        inlineData: {
          mimeType: 'image/jpeg', // Standardizing on JPEG for input
          data: base64Data
        }
      });
    });

    // 4. Call Google GenAI
    const startTime = Date.now();
    
    const response = await ai.models.generateContent({
      model: modelName || 'gemini-2.5-flash-image', // Default fallback
      contents: {
        parts: parts
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        }
      }
    });

    const endTime = Date.now();
    const duration = endTime - startTime;

    // 5. Extract Image
    let resultBase64 = '';
    const candidates = response.candidates;
    
    if (candidates && candidates.length > 0) {
        const content = candidates[0].content;
        if (content && content.parts) {
            for (const part of content.parts) {
                if (part.inlineData && part.inlineData.data) {
                    // Re-add prefix for frontend rendering
                    resultBase64 = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
                    break;
                }
            }
        }
    }

    if (!resultBase64) {
       return new Response(JSON.stringify({ error: 'No image generated by model' }), { status: 500 });
    }

    // 6. Return Clean Response
    return new Response(JSON.stringify({
      resultBase64,
      mimeType: 'image/png',
      timing: duration
    }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error: any) {
    console.error("Server Generation Error:", error);
    return new Response(JSON.stringify({ error: error.message || 'Internal Server Error' }), { status: 500 });
  }
}